name: Manual test workflow

on:
  workflow_dispatch:

jobs:
  windows-smoke-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: hello-world
        shell: bash        
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'    

      - name: NPM install
        run: |
          npm install
          
      - name: Run dev server
        run: |
          npm run start &
          
      - name: Basic dev server home test
        run: |
          curl --no-progress-meter http://localhost:3000/ --output home.txt
          ls -lh
          wc -l home.txt
          echo "Grepping home.txt"
          grep '/partial/Cars' home.txt
          
      - name: Basic dev server partial test
        run: | 
          curl --no-progress-meter http://localhost:3000/partial/Cars --output Cars.txt 
          echo "Grepping Cars.txt"          
          grep 'Volkswagen' Cars.txt
          
      - name: Basic dev server home test
        run: |
          curl --no-progress-meter http://localhost:3000/should/fail/does/it/error/action --output should-fail.txt
          echo "Grepping should-fail.txt"
          grep 'Will not have this' should-fail.txt
          

