name: Manual test workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: windows-2019

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
