name: Manual test workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./hello-world
        
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: List directory
      run: dir
    - name: NPM install (ci)
      run: npm ci
    - name: More steps 5
      run: dir
    - name: More steps 6
      run: npm run start
