name: Manual test workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: hello-world
        shell: bash        
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'    
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
      - name: List directory
        run: ls -lh
      - name: NPM install (ci)
        run: npm ci
      - name: More steps 5
        run: ls -lh
      - name: More steps 6
        run: npm run start



# name: smoke-test
# run-name: ${{ github.actor }} is running a smoke test
# 
# on:
#   workflow_dispatch:
#   
# jobs:
#   win-smoke-test:
#     runs-on: windows-2019
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - run: npm install -g bats
#       - run: bats -v    
